spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      # 파일 한 개당 최대 사이즈
      max-file-size: 20MB
      # 요청당 최대 파일 크기
      max-request-size: 100MB

# 상품 이미지 업로드 경로
itemImageLocation: C:/shop/item

# 리소스 업로드 경로
uploadPath: file:///C:/shop/

pagination:
  defaultPageSize: 10 # 기본 페이지 크기
  maxPage: 5 # 페이지 번호의 최대 개수

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace